name: autoRelease

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  set tag to release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2.3.2

      - name: Write release note
      - uses: metcalfc/changelog-generator@v0.4.3
        id: changelog
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
      - uses: actions/create-release@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false