name: Demo

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout private blog content
        uses: actions/checkout@v3
        with:
          repository: yi-Xu-0100/yixuju
          token: ${{ secrets.REPO_TOKEN }}
          path: exampleSite

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.80.0'

      - name: Build
        run: |
          cd exampleSite/
          rm -rf ./config.toml
          cp -f ../config.toml.example ./config.toml
          hugo

      - name: hugo-deploy-gh-pages
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exampleSite/public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: ${{ github.event.head_commit.message }}
