on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 17 * * *'
name: sync2gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2.3.2

    - name: Cache src repos
      uses: actions/cache@v2.1.1
      id: cache
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: ${{ runner.os }}-${{ github.repository_owner }}-${{ github.event.repository.name }}-cache

    - name: Print the cache status
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        echo "Cached successfully."

    - name: Mirror the Github repos to Gitee with cache
      uses: Yikun/hub-mirror-action@v0.09
      with:
        src: github/yi-Xu-0100
        dst: gitee/yiXu0100
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        cache_path: /github/workspace/hub-mirror-cache
        static_list: "${{ github.event.repository.name }}"
        force_update: true
    - name: Print cache path
      run: |
        ls -la ${{ github.workspace }}/hub-mirror-cache